version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "127.0.0.1:7777:5432"
    environment:
      POSTGRES_DB: minigigs
      POSTGRES_PASSWORD: verysecurepassword
      POSTGRES_USER: minigigs

  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.local
    command: docker/app/scripts/migrate_and_serve.sh
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
    volumes:
      - .:/app:ro
      - staticfiles:/var/www/static
      - mediafiles:/var/www/media
    environment:
      IN_DOCKER: 1
      DATABASE_URL: postgres://minigigs:verysecurepassword@postgres:5432/minigigs
      DEBUG: "true"
      SECRET_KEY: suitable-for-development-only
      STATIC_ROOT: /var/www/static
      MEDIA_ROOT: /var/www/media

volumes:
  staticfiles:
  mediafiles:
