# Generated by Django 3.0.2 on 2020-01-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import website.userprofile.models.profile


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('is_cyclist',
                 models.BooleanField(default=False, verbose_name='Is this a member of team?')),
                ('profile_picture',
                 models.ImageField(null=True,
                                   upload_to="",
                                   verbose_name='Profielfoto')),
                (
                    'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
