# Generated by Django 3.0.2 on 2020-01-27 18:02

from django.db import migrations

import website.utils.db_fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_create_userprofile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=website.utils.db_fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to='avatars', verbose_name='Profielfoto'),
        ),
    ]
