# Generated by Django 3.0.2 on 2020-01-27 14:00

from django.db import migrations
import website.utils.fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_squashed_0003_use_resized_image_field_for_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=website.utils.fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to='avatars', verbose_name='Profielfoto'),
        ),
    ]
