# Generated by Django 3.0.2 on 2020-01-27 13:45

from django.db import migrations
import website.utils.fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_update_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=website.utils.fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to='', verbose_name='Profielfoto'),
        ),
    ]
