# Generated by Django 3.0.2 on 2020-01-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.utils.fields.file_fields
import website.utils.fields.publication_date_field


class Migration(migrations.Migration):

    replaces = [('home', '0001_add_article_model'), ('home', '0002_allow_empty_cover_image'), ('home', '0003_allow_empty_cover_image'), ('home', '0004_use_custom_publication_datetime_field_squashed_0005_use_custom_publication_datetime_field_name'), ('home', '0005_use_auto_resize_image_field'), ('home', '0006_add_upload_to_destination_folder')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhoud')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('pubdate', website.utils.fields.publication_date_field.PublicationDateTimeField(null=True, verbose_name='Publicatiedatum')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
                ('is_published', models.BooleanField(default=True, verbose_name='Has this article been published?')),
                ('cover_image', website.utils.fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to='covers', verbose_name='Artikelfoto')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
    ]
