# Generated by Django 3.0.2 on 2020-01-25 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import website.home.models.article


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhoud')),
                ('creation_date',
                 models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True,
                                                 verbose_name='Publication date')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Last edited')),
                ('is_published', models.BooleanField(default=True,
                                                     verbose_name='Has this article been published?')),
                (
                'cover_image', models.ImageField(default='/static/images/photos/default_image.jpeg',
                                                 upload_to="covers",
                                                 verbose_name='Artikelfoto')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                             to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
    ]
