# Generated by Django 2.2.4 on 2019-08-27 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_adding_article_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Has this article been published?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_edit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last edited'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last edited'),
        ),
    ]
