# Generated by Django 3.0.2 on 2020-01-25 14:07

from django.db import migrations, models

import website.home.models.article


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_add_article_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(null=True,
                                    upload_to=website.home.models.article.cover_image_filename,
                                    verbose_name='Artikelfoto'),
        ),
    ]
