# Generated by Django 3.0.2 on 2020-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_create_photos_model'),
        ('home', '0001_create_article_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photos',
            field=models.ManyToManyField(related_name='articles', to='photos.Photo'),
        ),
    ]
