# Generated by Django 3.0.2 on 2020-01-25 14:16

from django.db import migrations, models

import website.home.models.article


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_allow_empty_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True,
                                    upload_to="covers",
                                    verbose_name='Artikelfoto'),
        ),
    ]
