# Generated by Django 3.0.2 on 2020-01-26 14:59

from django.db import migrations
import website.utils.fields.publication_date_field


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allow_empty_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubdate',
            field=website.utils.fields.publication_date_field.PublicationDateTimeField(null=True, verbose_name='Publication date'),
        ),
    ]
