# Generated by Django 3.0.2 on 2020-01-27 09:57

from django.db import migrations
import website.home.models.article
import website.utils.fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_use_custom_publication_datetime_field_squashed_0005_use_custom_publication_datetime_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=website.utils.fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to="cover", verbose_name='Artikelfoto'),
        ),
    ]
