# Generated by Django 3.0.2 on 2020-01-27 10:55

from django.db import migrations
import website.utils.fields.file_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_use_auto_resize_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=website.utils.fields.file_fields.ResizedHashNameImageField(blank=True, null=True, upload_to='covers', verbose_name='Artikelfoto'),
        ),
    ]
